version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "maticnetwork"
      RABBITMQ_DEFAULT_PASS: "maticnetwork"
    volumes:
      - /data/polygon/rabbitmq:/var/lib/rabbitmq
    expose:
      - 5672
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

  heimdalld:
    build:
      context: .
      dockerfile: Dockerfile
      target: heimdall
    ports:
      - 26657:26657
      - 26656:26656
    volumes:
      - /data/polygon/heimdalld:/data
    command:
      - start
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

  restserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: heimdall
    ports:
      - 1317:1317
    volumes:
      - /data/polygon/heimdalld:/data
    command:
      - rest-server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

  bridge:
    build:
      context: .
      dockerfile: Dockerfile
      target: bridge
    volumes:
      - /data/polygon/heimdalld:/heimdalld
      - /data/polygon/bridgedb:/bridgedb
    command:
      - start
      - --all
      - --home
      - /heimdalld
      - --bridge-db
      - /bridgedb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

  bor:
    build:
      context: .
      dockerfile: Dockerfile
      target: bor
    ports:
      - "30003:30003"
      - "8545:8545"
    volumes:
      - /data/polygon/bor:/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"
